version: "3.6"
services:
  thread-watcher:
    container_name: thread-watcher
    build:
      context: ./bot
      dockerfile: Dockerfile
    user: "1000:1000"
    restart: always
    volumes:
      - ./bot/data:/usr/src/bot/data
      - type: bind
        source: ./bot/config.json5
        target: /usr/src/bot/config.json5
    environment:
      - NODE_ENV=production

networks:
  default:
    driver: bridge
